### ISSUE TITLE
Aliasing in the proposed chessboard patterns

### ISSUE THREAD

**Issue by vincent-at** [dkogan/mrgingham#3]
I noticed there are aliasing (grey lines surrounding some of the chess square) on [your boards](https://github.com/dkogan/mrgingham/blob/master/chessboard.14x14.pdf).
Does it help improve the calibration?

I noticed [OpenCV chessboards](https://raw.githubusercontent.com/opencv/opencv/4.x/doc/pattern.png) have aliasing too, but not[ calib.io boards](https://calib.io/pages/camera-calibration-pattern-generator)

**Comment by dkogan** [comment]
Hi. There's no aliasing on my boards. It's a vector image with a bunch
of polylines, so any aliasing you see is coming from your pdf-viewing
program. Try another one?

**Comment by dkogan** [comment]
Closing this report. Please reopen if something more needs to be done.
